//
//  TabBFlowTests.swift
//  AsyncFlowExampleTests
//
//  Created by jimmy on 2026. 1. 3.
//

import AsyncFlow
@testable import AsyncFlowExample
import Testing

@MainActor
@Suite("TabB Flow Tests")
struct TabBFlowTests {
    @Test("TabBFlow - Screen1 네비게이션")
    func testNavigateToScreen1() async throws {
        // Given
        let flow = TabBFlow()
        let step = TabBStep.navigateToScreen1

        // When
        let contributors = flow.navigate(to: step)

        // Then
        #expect(flow.navigationController.viewControllers.count == 1)
        #expect(flow.navigationController.viewControllers.first is B_1ViewController)

        // Contributors 확인
        switch contributors {
        case .one:
            break // Success
        default:
            Issue.record("Expected .one contributor")
        }
    }

    @Test("TabBFlow - 여러 화면 순차 네비게이션")
    func sequentialNavigation() async throws {
        // Given
        let flow = TabBFlow()

        // When: B-1 → B-2 → B-3 → B-4 → B-5
        _ = flow.navigate(to: TabBStep.navigateToScreen1)
        _ = flow.navigate(to: TabBStep.navigateToScreen2)
        _ = flow.navigate(to: TabBStep.navigateToScreen3)
        _ = flow.navigate(to: TabBStep.navigateToScreen4)
        _ = flow.navigate(to: TabBStep.navigateToScreen5)

        // Then
        #expect(flow.navigationController.viewControllers.count == 5)
        #expect(flow.navigationController.topViewController is B_5ViewController)
    }

    @Test("TabBFlow - Pop 여러 단계")
    func popMultipleSteps() async throws {
        // Given
        let flow = TabBFlow()
        flow.animated = false
        _ = flow.navigate(to: TabBStep.navigateToScreen1)
        _ = flow.navigate(to: TabBStep.navigateToScreen2)
        _ = flow.navigate(to: TabBStep.navigateToScreen3)
        _ = flow.navigate(to: TabBStep.navigateToScreen4)

        #expect(flow.navigationController.viewControllers.count == 4)

        // When: 3단계 뒤로
        _ = flow.navigate(to: TabBStep.popViewController(count: 3))

        // Then
        #expect(flow.navigationController.viewControllers.count == 1)
        #expect(flow.navigationController.topViewController is B_1ViewController)
    }

    @Test("TabBFlow - 메타데이터 자동 생성 확인")
    func autoGeneratedMetadata() async throws {
        // Given
        let flow = TabBFlow()

        // When
        _ = flow.navigate(to: TabBStep.navigateToScreen3)

        // Then
        let metadata = flow.currentStackMetadata
        #expect(metadata.count == 1)

        // B_3ViewModel → "B-3"
        #expect(metadata[0].identifier == "B_3ViewModel")
        #expect(metadata[0].displayName == "B-3")
    }
}
